### ISSUE TITLE
2b week2 分組任務

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cd2018#14]
請各組利用程式方法, 取得各組學員名單, 以 html 列出各組組序與組員學號, 並且列出電腦教室的班級座位表.

參考:

https://ethercalc.org/f2v1ah61axug

# 參考解題方法

當各組要提出此一分組任務的解題方法前, 必須要整理一下各學員所提出的 Concept (概念) 以及所具備可以解決問題的 Knowledge (知識), 所謂概念就是分組學員提出可能的解題想法, 但因為尚未經過驗證, 因此這些概念一旦以口語、文字、 2D/3D 檔案、初步的數學分析或其他實作, 逐步通過驗證能夠解決問題後, 就可以轉化進入各組的知識庫, 之後就可以用來解決類似的任務問題.

# 解題概念

1. 希望提出可以讓各組學員自行輸入座位與學號, 無需由其他人員代為輸入或進行資料處理.
2. 假如各學員可以同時在一個線上表格輸入座位與學號, 這樣的即時協同擷取資料模式, 將會省下許多處理時間.
3. 當所有使用者輸入資料後, 假如能夠透過程式方法列出分組資料, 其中包含組別與組員學號, 並且列出各學員的座位表, 將有助隨後課程進行之用.

# 所具備知識

1. 可以使用 https://ethercalc.net/ 建立一個線上即時試算表, 要求各組學員即時在試算表中, 按照座位輸入學號, 並以每張桌子上的至多三名組員為同一組.
2. 當各組完成學員學號輸入後, 從線上取出座位表資料, 存成文字檔案後, 以可攜程式環境中的 Python 程式進行解讀分析後, 列出座位表以及分組表.
3. 從網際內容管理及電腦輔助設計實習課程中, 了解可以利用 Flask 框架, 編寫 Server based 應用程式, 並且可以使用 https://www.heroku.com/, 將各班分組資料以及 Python 程式部署在雲端, 若程式提供上傳功能 , 各班分組時就可以將資料檔案上傳後, 利用雲端程是進行分組表與座位表的列印.
4. 初步第 3 項知識, 可以再延伸使用者管理模組, 也能採用 https://oauth.net/2/ 方法, 讓使用者透過 Github, Facebook 或 Gmail 帳號登入雲端系統後, 依照所授予的權限處理相關資料.
5. 各組在進行此一任務解題過程, 因為組員人數不到五人, 因此可以採用 https://www.gitbook.com/pricing 在網路上編寫任務報告, 設法產生 html 以及 pdf 格式的任務報告.

# CK 設計原理的轉化

1. http://www.cktheory.com 明確點出, 若以數學的集合論來收集協同產品設計流程中的概念與知識, 理論上, 各組可以擁有無限大數量的概念, 以及無限大數量的知識, 但是限於產品開發有各項資源, 包括時間、人力、可用資源等地限制, 因此各組必須在這些有限資源的約束下, 整理有限的想法概念, 並且列出有限數量的解題用知識, 以便在規定時效內, 以所規劃套用的資源完成任務解題.
2.  根據 CK design theory 中的論述, 可以將概念轉化為知識, 概念可以衍生出更多概念, 知識可能成為概念, 而且知識可能衍生出更多知識.
3. 根據上述知識 1 中所提出的 https://ethercalc.net/, 所能夠轉化出的其他解題概念為, 若能在目前 Ethercalc 的功能架構下, 提供 server based 的權限管理以及資料存取, 此一系統將可解決線上即時分組問題外, 還能用於其他需要同步協同產品開發流程中使用, 例如, 各學員可以同步及時利用此一系統處理文字或 Python 或 Javascript 程式編寫與測試流程, 此外, 若此同步程式架構可以延伸到 2D/3D 繪圖, 各學員便可以直接在線上同步檢視或存取相關 2D/3D 產品的零組件檔案, 例如: http://ghemingway.github.io/cad.js/ 所呈現的零件, 可以由各學員依權限即時上傳管理組合.
4. Flask 的 Python 程式屬於 server based 架構, 若能在此一系統引入 https://brython.info/, 使用者就可以得到類似 https://nodejs.org/en/, 前後端都使用 Python 程式語法, 系統緊密整合的好處.
5. https://www.gitbook.com/pricing 免費帳號只限五人協同, 若各組能夠進一步檢視利用 LaTeX (例如: https://miktex.org/ 處理 Markdown 為 html 與 pdf 的流程, 並且引入 https://pandoc.org/, 就可以自行獨力建立一套能夠客製化處理協同機電資產品設計流程需要的報告文件處理系統.

**Comment by s40523201** [comment]
第二組倉儲連結 : https://github.com/s40523201/cd2018

with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])
               

 第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250

**Comment by s40523201** [comment]
<pre><code>with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])
               </code></pre>
 第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250

**Comment by 40523249** [comment]
第14組
<pre><code>with open("2b_raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])<pre>

**Comment by s40523209** [comment]
[第一組協同倉儲](https://github.com/s40523209/cd2018)

```javascript
with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])
```

```

第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250

```

**Comment by s40523236** [comment]
[第九組倉儲](https://github.com/s40523236/cd2018)

```

with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])

```

```
第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250
```

**Comment by s40523242** [comment]
[第12組倉儲](https://github.com/s40523242/cd2018)

```

with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])

```


```
第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250
```

**Comment by s40523206** [comment]
[第十組協同倉儲](https://github.com/s40523206/cd2018_team_10)

<pre><code>with open("320.txt") as fh:
--
  | # 逐行讀出檔案資料, 並放入數列中
  | lines = fh.readlines()
  | # 設法用迴圈逐數列內容取出字串
  | # 組序變數 g 起始值設為 0
  | g = 0
  | for i in range(len(lines)):
  | # 利用 strip() 去除各行字串最末端的跳行符號
  | #print(lines[i].strip())
  | line = lines[i].strip()
  | # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
  | groups = line.split("\t")
  | #print(groups)
  | for i in range(len(groups)):
  | # 每組有三名組員
  | if i%3 == 0:
  | # 每三位組員組序增量 1
  | g += 1
  | print()
  | print("第" + str(g) + "組:")
  | print(groups[i])
  | else:
  | print(groups[i]) </code></pre>


<pre><code> 第1組:
--
  | 40523207
  | 40523209
  |  
  | 第2組:
  | 40523203
  | 40523201
  | 40523240
  |  
  | 第3組:
  | 40523216
  | 40523232
  | 40523213
  |  
  | 第4組:
  | 40523204
  | 40523219
  |  
  | 第5組:
  | 40523211
  | 40523215
  | 40523245
  |  
  | 第6組:
  | 40523226
  | 40523227
  | 40523231
  |  
  | 第7組:
  | 40523222
  | 40523210
  | 40523224
  |  
  | 第8組:
  | 40523220
  | 40523214
  | 40523218
  |  
  | 第9組:
  | 40523233
  | 40523236
  | 40523243
  |  
  | 第10組:
  | 40523205
  | 40523206
  | 40523230
  |  
  | 第11組:
  | 40523238
  | 40523244
  | 40523239
  |  
  | 第12組:
  | 40523212
  | 40523241
  | 40523242
  |  
  | 第13組:
  | 40523246
  | 40523234
  | 40523237
  |  
  | 第14組:
  | 40523248
  | 40523249
  | 40523250<pre><code></code></pre></code></pre>

**Comment by s40523211** [comment]
[第五組協同倉儲](https://github.com/s40523211/cd2018)
``` 
with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i])
```
```
第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250
```

**Comment by s40523206** [comment]
第十組協同倉儲(https://github.com/s40523206/cd2018_team_10)

<pre><code>with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i]) <pre><code>

<pre><code> 第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250<pre><code></code></pre></code></pre>

**Comment by s40523220** [comment]
with open("2b-raw.txt") as fh:
        # 逐行讀出檔案資料, 並放入數列中
        lines = fh.readlines()
        # 設法用迴圈逐數列內容取出字串
        # 組序變數 g 起始值設為 0
        g = 0
        for i in range(len(lines)):
            # 利用 strip() 去除各行字串最末端的跳行符號
            #print(lines[i].strip())
            line = lines[i].strip()
            # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
            groups = line.split("\t")
            #print(groups)
            for i in range(len(groups)):
                # 每組有三名組員
                if i%3 == 0:
                    # 每三位組員組序增量 1
                    g += 1
                    print()
                    print("第" + str(g) + "組:")
                    print(groups[i])
                else:
                   print(groups[i]) 


    第1組:
    40523207
    40523209

    第2組:
    40523203
    40523201
    40523240

    第3組:
    40523216
    40523232
    40523213

    第4組:
    40523204
    40523219

    第5組:
    40523211
    40523215
    40523245

    第6組:
    40523226
    40523227
    40523231

    第7組:
    40523222
    40523210
    40523224

    第8組:
    40523220
    40523214
    40523218

    第9組:
    40523233
    40523236
    40523243
  
    第10組:
    40523205
    40523206
    40523230

    第11組:
    40523238
    40523244
    40523239

    第12組:
    40523212
    40523241
    40523242

    第13組:
    40523246
    40523234
    40523237

    第14組:
    40523248
    40523249
    40523250

**Comment by s40523246** [comment]
[第13組協同倉儲](https://github.com/s40523237/2018cdb.no13)

<pre><code>with open("2b-raw.txt") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    # 設法用迴圈逐數列內容取出字串
    # 組序變數 g 起始值設為 0
    g = 0
    for i in range(len(lines)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        #print(lines[i].strip())
        line = lines[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = line.split("\t")
        #print(groups)
        for i in range(len(groups)):
            # 每組有三名組員
            if i%3 == 0:
                # 每三位組員組序增量 1
                g += 1
                print()
                print("第" + str(g) + "組:")
                print(groups[i])
            else:
               print(groups[i]) 
</code></pre>

<pre><code>
第1組:
40523207
40523209

第2組:
40523203
40523201
40523240

第3組:
40523216
40523232
40523213

第4組:
40523204
40523219

第5組:
40523211
40523215
40523245

第6組:
40523226
40523227
40523231

第7組:
40523222
40523210
40523224

第8組:
40523220
40523214
40523218

第9組:
40523233
40523236
40523243

第10組:
40523205
40523206
40523230

第11組:
40523238
40523244
40523239

第12組:
40523212
40523241
40523242

第13組:
40523246
40523234
40523237

第14組:
40523248
40523249
40523250</code><pre>
