### ISSUE TITLE
cd-week5 報告

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cd2018#22]
# 協同資料處理

請根據[二乙第五週第一堂課到課名單](https://github.com/mdecourse/wcms-scrum3/blob/master/cd_w5b.txt), 直接在各組 gh-pages 網頁或雲端主機上列出第一堂課缺席名單, 完成後, 將詳細處理過程、討論與心得放入各組的 Gitbook, 並將所完成的網址與 Gitbook 章節呈現在下列回應中.

參考答案, 寫成[雲端程式](https://github.com/mdecourse/wcms-scrum3)後[連結](http://wcms-scrum3.herokuapp.com/w5cdb):

[w7_cda.txt](https://github.com/mdecourse/wcms-scrum3/blob/master/cd_w7a.txt), [w7cda 雲端連結](http://wcms-scrum3.herokuapp.com/w7cda)

    with open("cd_w5b.txt", "r", encoding="utf-8") as fh:
        # 逐行讀出檔案資料, 並放入數列中
        lines = fh.readlines()
        raw_data = lines[1:]
        #print(raw_data)
        # 設法用迴圈逐數列內容取出字串
        # k 為集合所有檔案中的學號字串, 先設為空字串
        k = []
        for i in range(len(raw_data)):
            # 利用 strip() 去除各行字串最末端的跳行符號
            raw_line = raw_data[i].strip()
            # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
            groups = raw_line.split("\t")
            #print(groups)
            # 逐一進入各行中的各字串去除空字串
            for j in range(len(groups)):
                if groups[j] != "":
                    # 除了空字串外, 其餘字串放入 k 數列中
                    k.append(groups[j])
    # 將 k 中只出現一次的字串印出, 即為缺席者名單
    absent = [x for x in k if k.count(x) == 1]
    print(absent)

**Comment by s40523219** [comment]
[https://www.gitbook.com/book/s40523219/cd2018_bp4/edit#/edit/master/week-5.md?_k=ayecx7]第四組
 GitBook(url)

**Comment by s40523226** [comment]
第六組二乙
[gitbook](https://www.gitbook.com/book/s40523226/ball-movement-system/edit#/edit/master/README.md?_k=igfkh3)

**Comment by s40523230** [comment]
[第十組gitbook](https://www.gitbook.com/book/s40523205/cd2018/details)

**Comment by s40523211** [comment]
[第5組gitbook](https://s40523211.gitbooks.io/cd2018/content/w5.html)

**Comment by s40523210** [comment]
[二乙第七組](https://s40523210.gitbooks.io/g7_gitbook/content/ti-qiu-ji-gou/week5.html)

**Comment by s40523209** [comment]
[乙班第一組gitbook](https://www.gitbook.com/book/s40523209/bg1/details)

**Comment by s40523119** [comment]
這次的自評作業，難度提升很多，除了撰寫 `python`之外，還得使用 `flask` 佈署到 `heroku`上，並且在遠端執行程式代碼，顯示出本次作業內容。對於大部分的同學，就像是無字天書一樣，當中我也跳了很多坑，花了一些時間解決問題，之後再將詳細的內容更新至網誌以及Gitbook上。


- 使用遠端執行的程式碼如下:

```python
@app.route('/cdw5/')
def cdw5():
    with open(os.path.join(APP_STATIC, 'cdw5b.txt'), 'r', encoding="big5") as fh:
        data = fh.readlines() #逐行讀入
        data = [data[i].strip() for i in range(len(data))][1:]# 去除跳行字符以及跳過第一段中文字
    list = [] #出席與修課總名單
    for i in range(len(data)):
        item = data[i].split('\t\t')
        list.extend(item)
    absent = [x for x in list if list.count(x) == 1]
    return render_template('cdw5.html', absent=absent)
```

[展示網頁](https://cd2018.herokuapp.com/cdw5/)

目前已經實現登入、登出、新增以及刪除資料的功能，之後會將 markdown編輯器整合上去，變成真正線上的部落格。

**Comment by mdecourse** [comment]
呵呵, 無字天書的形容可能正恰如其分, 機械設計工程師在電資相關技術不斷推陳出新的情況下, 必須要自學、執行與想像三力不斷並進, 而自學需要有英文與數學的基本能力, 執行則需要虛實融合, 而想像力則必須要與前兩力互為因果且不受限, 真的不容易啊!

大家參考一下: http://wcms-scrum3.herokuapp.com

**Comment by s40523123** [comment]
作業內容請學生們透過`heroku`將`flask`佈署到其中，而在網頁展示的內容中，我們要利用`python`寫出如同老師給的例子，將二乙第一堂課缺席名單輸出結果。

首先`falsk`的建立由[flask官方網站](http://flask.pocoo.org/docs/0.12/)的教學著手，依照步驟成功在cmd.exe(或隨身系統)中執行`flask run`後便可在近端編輯生成的網頁。

建立完成後將其佈署至`heroku`上，由[Heroku官方網站](https://devcenter.heroku.com/)的教學進行流程，官方使用`Django`做架構，而我們使用的`flask`需由[此教學連結](https://github.com/mdecourse/wcms2018/tree/gh-pages/heroku/wcms-scrum3)來依步驟執行。

最後在`heroku`上，能夠展示出自己由`flask`建構的網頁，[我的連結在此](https://kuanru.herokuapp.com/)。
其中內容由官方網站教學，呈現登入、登出功能，以及留下簡易訊息(Title、Text)的功能。
作業需在此網頁中執行`python`將缺席名單展現，以及在`gitbook`中新增心得，此部分在之後會補上。

在此挑選`flask`中，登入及登出的程式碼做簡易展示([說明連結](http://flask.pocoo.org/docs/0.12/tutorial/views/#tutorial-views))：
登入：
```python
@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != app.config['USERNAME']:
            error = 'Invalid username'#輸入帳號錯誤時顯示訊息
        elif request.form['password'] != app.config['PASSWORD']:
            error = 'Invalid password'#輸入密碼錯誤時顯示訊息
        else:
            session['logged_in'] = True#若沒錯誤則會登入
            flash('You were logged in')#並顯示您已登入的訊息
            return redirect(url_for('show_entries'))
    return render_template('login.html', error=error)
```
登出：
```python
@app.route('/logout')
def logout():
    session.pop('logged_in', None)#pop指令會將先前的logged_in去除,即為logout狀態
    flash('You were logged out')#登出訊息
    return redirect(url_for('show_entries'))
```
[網頁連結](https://kuanru.herokuapp.com/)
USERNAME=admin
PASSWORD=40523123

以上感謝 @s40523119 教學，大家快去灌爆他訊息。

**Comment by s40523104** [comment]
第三組 gitbook (補)
[老師好帥](https://legacy.gitbook.com/book/s40523104/cd_w7/details)

**Comment by s40523124** [comment]
[第八組 gitbook-w7](https://s40523118.gitbooks.io/ag8-report/content/week7/40523124.html)

**Comment by s40523135** [comment]
第四組gitbook鏈接[https://legacy.gitbook.com/book/s405231351/2018scd-notes/edit#/edit/master/week5.md?_k=c91rq6]
今天試試看發現老師給的程式在近端可以執行，但是放在FLASK中執行時CMD會報錯，這點暫時無法解決。

from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

@app.route('/cdw5/cdw6/')
def cdw6():
    with open("cdw5b.txt", "r", encoding="utf-8") as fh:
    # 逐行讀出檔案資料, 並放入數列中
    lines = fh.readlines()
    raw_data = lines[1:]
    #print(raw_data)
    # 設法用迴圈逐數列內容取出字串
    # k 為集合所有檔案中的學號字串, 先設為空字串
    k = []
    for i in range(len(raw_data)):
        # 利用 strip() 去除各行字串最末端的跳行符號
        raw_line = raw_data[i].strip()
        # 利用 split() 將以 \t 區隔的字串資料分離後納入 groups 字串
        groups = raw_line.split("\t")
        #print(groups)
        # 逐一進入各行中的各字串去除空字串
        for j in range(len(groups)):
            if groups[j] != "":
                # 除了空字串外, 其餘字串放入 k 數列中
                k.append(groups[j])
# 將 k 中只出現一次的字串印出, 即為缺席者名單
absent = [x for x in k if k.count(x) == 1]
print(absent)

if __name__ == '__main__':
    app.run()
希望老師可以幫忙看一下

File "aa.py", line 24
    lines = fh.readlines()
這是報錯信息

**Comment by s40523243** [comment]
[乙班第九組](https://legacy.gitbook.com/book/s40523236/cd2018/edit#/edit/master/week-5.md?_k=z1vdx7)

**Comment by s40523246** [comment]
[乙班第十三組](https://legacy.gitbook.com/book/s40523237/2018cdb-no-13/edit#/edit/master/week5.md?_k=e6l692)

**Comment by s40523133** [comment]
[甲班第12組倉儲](https://github.com/s40523139/cd2018)
[練習結果呈現in gitbook](https://legacy.gitbook.com/book/s40523139/group-12/details)

**Comment by s40523125** [comment]
[甲班第七組Gitbook](https://s40523125.gitbooks.io/cd2018/content/w1.html)

**Comment by s40523232** [comment]
(乙班第三組gitbook){https://legacy.gitbook.com/book/s40523232/-gitbook/details}
