### ISSUE TITLE
2a 期中報告

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cd2018#24]
# [分組期中報告](https://github.com/mdecourse/cd2018/issues/23#issue-312456994)

請在期中考週上課之前, 回報各組與各組員的期中報告與自評

**Comment by s40523124** [comment]
[二甲第8組GitBook](https://s40523118.gitbooks.io/ag8-report/content/midterm/tai-qiu-ji-gou.html)

**Comment by s40523132** [comment]
[第六組期中報告](https://legacy.gitbook.com/book/s40523136/g6-gitbook/details)

**Comment by s40523118** [comment]
[第八組期中報告](https://legacy.gitbook.com/book/s40523118/ag8-report/details)

**Comment by s40523117** [comment]
<a href="https://cd2018.gitbook.io/ball-movement-system/">第四組期中報告</a>

**Comment by s40523139** [comment]
[第十二組期中報告](https://legacy.gitbook.com/book/s40523139/group-12/details)

**Comment by s40523129** [comment]
[第11組gitbook期中報告](https://s40523143.gitbooks.io/cd2018/content/qi-zhong-bao-gao.htmll)

**Comment by s40523143** [comment]
[第11組期中報告](https://s40523143.gitbooks.io/cd2018/content/qi-zhong-bao-gao.html)

**Comment by s40523119** [comment]
[第九組期中報告](https://s40523119.gitbook.io/cd2018/)

組員自評:
40523119 林建安 85
40523120 侯安調 60
40523121 施恩澤 70

**Comment by s40523125** [comment]
[第七組期中報告](https://s40523125.gitbooks.io/cd2018/content/w9-qi-zhong-fen-zu-bao-gao.html)

**Comment by s40523107** [comment]
[https://ball.gitbooks.io/cd2018/content/qi-zhong-bao-gao.html](第十組期中報告)

**Comment by s40523141** [comment]
[第二組期中報告](https://s40523141.gitbooks.io/g2-gitbook/content/2018scd.html)

**Comment by s40523146** [comment]
[第五組期中報告](https://s40523145.gitbooks.io/-2018cd/content/2018cdqi-zhong-bao-gao.html)

**Comment by S40523102** [comment]
[第三組期中報告](https://legacy.gitbook.com/book/s40523104/middle/details)

**Comment by s40523134** [comment]
[第十四組期中報告](https://2018scd_no-13.gitbooks.io/2018scd-no14/content/qi-zhong-bao-gao.html)

**Comment by s40523115** [comment]
[第三組期中報告](https://legacy.gitbook.com/book/2018g3/cd2018/details)

**Comment by s40523142** [comment]
[第十三組期中報告](https://legacy.gitbook.com/book/git-clone-team14/cd2018-team13/details)

**Comment by mdecourse** [comment]
W10

11, 32, 36, 45, 46, 19, 24, 18, 17, 26, 43, 33, 39, 30, 28, 7, 31, 6, 34, 38, 13, 21, 1, 41, 22
