### ISSUE TITLE
2b 期中報告

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cd2018#25]
# [分組期中報告](https://github.com/mdecourse/cd2018/issues/23#issue-312456994)

請在期中考週上課之前, 回報各組與各組員的期中報告與自評

**Comment by s40523243** [comment]
二乙第九組
[gitbook](https://s40523243.gitbooks.io/-gitbook/content/)

**Comment by s40523201** [comment]
二乙第二組
[gitbook](https://s40523203.gitbooks.io/2b-group2/content/gang-qiu-xun-huan-ji-gou-bao-gao.html)

**Comment by s40523209** [comment]
[二乙第一組gitbook](https://s40523209.gitbooks.io/bg1/content/qi-zhong-bao-gao-1.html)

**Comment by s40523243** [comment]
[二乙第九組](https://s40523243.gitbooks.io/-gitbook/content/week7/q1.html)

**Comment by s40523232** [comment]
[乙班第三組gitbook](https://legacy.gitbook.com/book/s40523232/123/details)

**Comment by s40523224** [comment]
[四設二乙第7組](https://legacy.gitbook.com/book/s40523210/g7_gitbook/details)

**Comment by s40523205** [comment]
[二乙第10組](https://legacy.gitbook.com/book/s40523205/cd2018/details)

**Comment by s40523245** [comment]
[二乙第5組](https://legacy.gitbook.com/book/s40523211/cd2018/details)

**Comment by s40523220** [comment]
<p><a href="https://www.gitbook.com/book/s40523220/cd2018/details">第8組gitbook</a></p>

**Comment by 40523249** [comment]
[二乙第14組](https://legacy.gitbook.com/book/405232491/cd_2018_team14/details)

**Comment by s40523238** [comment]
[二乙 第11組](https://www.gitbook.com/book/s40523244/ag11-gitbook/details)

**Comment by s40523204** [comment]
[二乙第4組](https://legacy.gitbook.com/book/s40523219/cd2018_bp4/details)

**Comment by s40523246** [comment]
[二乙第十三組](https://legacy.gitbook.com/book/s40523237/2018cdb-no-13/details)
