### ISSUE TITLE
2a 組員期末報告影片回報區

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cd2018#35]
請 2a 各組組員在期末考週之前, 將 3-5 分鐘期末報告影片上傳到 Youtube 後, 在下列回報連結.

# 請在影片標題註明: 國立虎尾科技大學 - 機械設計工程系 - 協同產品設計實習 - 學號 期末報告

# 並在影片說明欄位附上最後完成的 V-rep ttt 檔案連結, 以利評分.

**Comment by s40523122** [comment]
這學期的課程也到尾聲了，對於這學期的作品我算是蠻滿意的，雖然能改善的地方還很多，在這門課中我做了許多第一次的嘗試，而我也將心得拍攝成影片放於 https://www.youtube.com/watch?v=213GSb0rsco 中。
最後做個總結，我認為我在這堂課學到最多的不是程式軟體的使用，而是勇於嘗試的毅力還有──不對自己不熟悉的事物做出抱怨的想法！

**Comment by s40523136** [comment]
[期末報告影片](https://youtu.be/QvGfQTNK6NA)
在這次專題中，讓我們有機會學習到了不同領域的專業知識，讓許多不同領域的東西與機械設計做連結，不但使我們的作品有了更多不同的可能性與變化性，也讓我們學習到了更多不一樣的專業知識，這些技術跟經驗相信在未來都能為自己帶來很大的幫助，也能隨著自己所學的越多，讓更多不同領域的知識與經驗做接軌，就能創造研發出更多不同的想法與創意，並將這些知識廣泛運用到各個地方。

**Comment by s40523132** [comment]
[期末報告影片](https://youtu.be/AxyKGlBGJJY)

**Comment by s40523104** [comment]
這學期的[期末報告影片](https://youtu.be/miFgzLhZZh4)

**Comment by s40523145** [comment]
[期末報告影片](https://www.youtube.com/watch?v=hIpk5JuaXg0&feature=youtu.be)

**Comment by s40523135** [comment]
[期末報告影片](https://www.youtube.com/watch?v=-3V17befKXQ&feature=youtu.be)
這分學期中我們從一開始的網際程式的使用到學期中段小組内的小協同，比如[gitbook](https://cd2018.gitbook.io/ball-movement-system/week-notes/w10)的編寫，小組協同倉儲[cd2018](https://github.com/s40523135/cd2018)的管理。並在期中之後做了很多機構的練習。最後在一個大的環境，兩個班一起的協同，熟悉了資料的衝突處理，以及推送pull request 。這樣就可以讓我們以後如果在工作中遇到全公司甚至世界各地不同國家的人一起協同的時候不會無法融入到協同的環境中去。

**Comment by s40523124** [comment]
[期末報告](https://youtu.be/SzwWCp2OXMg)

**Comment by s40523130** [comment]
[期末報告影片](https://youtu.be/UgeQgNtsqH8)

**Comment by s40523113** [comment]
[期末報告影片](https://youtu.be/xrpP-gJSQwQ)

**Comment by s40523138** [comment]
[期末報告影片](https://youtu.be/QCmoFVwxWpQ)

**Comment by s40523129** [comment]
[期末報告影片](https://www.youtube.com/watch?v=Y8X7zVUqbvM&t=11s)

**Comment by s40523143** [comment]
[40523143期末報告影片](https://www.youtube.com/watch?v=7UVJ4MK7hNY)

**Comment by s40523146** [comment]
[期末報告影片](https://www.youtube.com/watch?v=55rnA-nECno&feature=youtu.be)

**Comment by s40523123** [comment]
[期末影片](https://www.youtube.com/watch?v=mVt2bmJ_9AE&feature=youtu.be)

**Comment by s40523101** [comment]
[期末報告影片](https://www.youtube.com/watch?v=Pgc6_eDM0HY&feature=youtu.be)

**Comment by s40523133** [comment]
[期末報告影片](https://www.youtube.com/watch?v=VlLQ6XgWKKU&feature=youtu.be)

**Comment by s40523118** [comment]
[期末報告影片](https://www.youtube.com/watch?v=WAPFfbmmF0U)

**Comment by s40523128** [comment]
[期末報告影片](https://youtu.be/4CqkObV3ufY)

**Comment by s40523134** [comment]
[期末報告影片](https://www.youtube.com/watch?v=VwhQba2ukEU&feature=youtu.be)

**Comment by s40523117** [comment]
<a href="https://www.youtube.com/watch?v=pG8zTL7aYcw&feature=youtu.be">期末報告影片</a>

**Comment by s40523107** [comment]
[https://youtu.be/Z-nRwl0QVA4](期末報告影片)

**Comment by s40523111** [comment]
[期末報告影片](https://www.youtube.com/watch?v=8HVLogbhyIk)

**Comment by S40523102** [comment]
[期末報告影片](https://youtu.be/1vq5E-Ugobc)

**Comment by s40523119** [comment]
[期末報告影片](https://youtu.be/eXSfk-bYiYc)

**Comment by s40523139** [comment]
[期末報告影片](https://www.youtube.com/watch?v=qfmNqOTeM5M)

**Comment by s40523141** [comment]
[期末報告影片](https://www.youtube.com/watch?v=tUHxKA5gBeg)

**Comment by s40523106** [comment]
[期末報告影片](https://www.youtube.com/watch?v=OQSUCpH9_uI&feature=youtu.be)

**Comment by s40523121** [comment]
[期末報告影片](https://www.youtube.com/watch?v=mOTLmhxwtRY)

**Comment by s40523125** [comment]
[期末報告影片](https://www.youtube.com/watch?v=OtmsF1VVJUE&feature=youtu.be)

**Comment by s40523127** [comment]
[期末報告影片](https://www.youtube.com/watch?v=mdjnQ5a5YlE&t=237s)

**Comment by s40523120** [comment]
[期末報告影片](https://youtu.be/Ea4vHaG1g5U)

**Comment by s40523115** [comment]
[期末報告影片](https://www.youtube.com/watch?v=6otKoOC3QVQ&feature=youtu.be)
